# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: ddd-rails-monolith_development

test:
  <<: *default
  database: ddd-rails-monolith_test

production:
  <<: *default
  database: ddd-rails-monolith_production
  username: ddd-rails-monolith
  password: <%= ENV['DDD-RAILS-MONOLITH_DATABASE_PASSWORD'] %>
